version: '3.8'

services:
  valkey:
    image: valkey/valkey:latest
    container_name: ml-trading-valkey
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./data/valkey:/data
    command: >
      valkey-server
      --maxmemory 4gb
      --maxmemory-policy allkeys-lru
      --save 60 1000
      --save 300 10
      --save 3600 1
      --appendonly yes
      --appendfsync everysec
    environment:
      - VALKEY_REPLICATION_MODE=master
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  valkey-data:
    driver: local
